modify: add data crawler and del another scraper
TonysHub/subway pull request #17
Opened 2023-05-02 13:36 UTC by usiohc

subway_traffic_daily.csv, subway_traffic_month_hourly.csv
생성 확인 부탁드립니다. error 발생시 내용좀 남겨주세요!

이해 안가시는 소스코드 리뷰 남겨주세요!

**venv 환경에서 `python crawler.py`**

2023-05-02 14:19 UTC, Jeon-peng reviewed
고생 많으셨습니다!! 코드 돌리는데 문제는 없었습니다 !!
: D

2023-05-02 14:19 UTC, Jeon-peng commented on project/crawler.py
> +import numpy as np
numpy 사용 안하는 것 같습니다!

2023-05-02 15:25 UTC, TonysHub requested changes
고생하셨어요 ㅠ 😿 

테스트 코드:
```
# 홈페이지에서 받은 데이터
validation = pd.read_csv("subway_users_daily.csv", encoding='cp949') 
# 크롤러 데이터
test = pd.read_csv("subway_traffic_daily.csv", encoding='utf-8')

validation["사용일자"] = pd.to_datetime(validation["사용일자"], format="%Y%m%d")

def validate(line, date):
    assert validation[(validation["호선명"] == line) & (validation["사용일자"] <= date)]["승차총승객수"].sum() == test[(test["line"] == line) & (test["date"] <= date)]["people_in"].sum(), "승차인원 불일치"
    assert validation[(validation["호선명"] == line) & (validation["사용일자"] <= date)]["하차총승객수"].sum() == test[(test["line"] == line) & (test["date"] <= date)]["people_out"].sum(), "하차인원 불일치"
    assert validation[(validation["호선명"] == line) & (validation["사용일자"] <= date)].count() == test[(test["line"] == line) & (test["date"] <= date)].count(), "데이터 수 불일치"

validate("3호선", "2023-04-21")

>>> AssertionError: 승차인원 불일치
```

예를 들어,
```
validation[(validation["호선명"] == "3호선") & (validation["사용일자"] <= "2023-04-19")]["승차총승객수"].sum()
>>> 15964230
```
```
test[(test["line"] == "3호선") & (test["date"] <= "2023-04-19")]["people_in"].sum()
>>> 2134415
```

크롤러 데이터가 더 작은 것 같습니다 ㅠㅠ 테스팅 방법이 잘못 됐을 수도 있는데 한번 검토 부탁드려요!

2023-05-02 15:25 UTC, TonysHub commented on project/crawler.py
> +    for line in lines:
여기에서 `df_std`에 concat 하는 것 보다, 루프 한번 끝날 때마다 csv 자체에 저장하고, 
csv에 append 하는게 효율성에 좋아보입니다!

https://stackoverflow.com/questions/17530542/how-to-add-pandas-data-to-an-existing-csv-file

2023-05-02 15:25 UTC, TonysHub commented on project/crawler.py
> +from selenium.webdriver.support.ui import WebDriverWait
python version 이랑 Selenium version 체크 부탁드려요~

`support.ui`가 셀레니움 4.0에서 deprecated 됐다고 해서, 저는 해당 코드를

`from selenium.webdriver.support.wait import WebDriverWait`
`from selenium.webdriver.support.select import Select`로 바꿨습니다

2023-05-02 15:25 UTC, TonysHub commented on project/crawler.py
> +    df_std = pd.DataFrame() # subway_traffic_daily -> std
프로덕션에 올릴때는 모든 네이밍을 풀 네임으로 부탁드립니다.

`df_subway_traffic_daily` 

참고자료:
https://google.github.io/styleguide/pyguide.html#316-naming
https://peps.python.org/pep-0008/#naming-conventions

2023-05-02 16:49 UTC, Jeon-peng commented on project/crawler.py
> +
한글로 나와있는 승차인원, 하차인원 컬럼 수정했으면 좋겠습니다. 
140 이후에 코드 추가하면 좋을 것 같습니다.
제 로컬에서는 잘 돌아가는거 확인했습니다!

```
new_columns = []
for item in df_stmh.columns:
    if '승차' in item:
        new_columns.append('in_' + item[:2] + '_' + item[4:6])
    elif '하차' in item :
        new_columns.append('out_' + item[:2] + '_' + item[4:6])
    else:
        new_columns.append(item)
        
df_stmh.columns = new_columns

```

2023-05-03 01:13 UTC, usiohc commented on project/crawler.py
> +    for line in lines:
넵, 오늘 스탠드업 미팅때 정현님과 정확하게 얘기 나눠서 csv를 사용하게되면 해당 코드 변경하겠습니다!

2023-05-03 01:13 UTC, usiohc commented on project/crawler.py
> +from selenium.webdriver.support.ui import WebDriverWait
![image](https://user-images.githubusercontent.com/89768234/235815894-62eb78bd-085f-4702-ab36-f44307b8b71c.png)

![image](https://user-images.githubusercontent.com/89768234/235815861-b123cd21-7542-4b6d-b1b4-a78e5b5c1e32.png)

python, selenium verion은 위와 같습니다! 

selenium은 처음 requirements로 모든 라이브러리를 설치하고 따로 건드린게 없었습니다!
python은 같은 major version으로 문제되어 보이진 않습니다!

2023-05-03 01:36 UTC, TonysHub commented on project/crawler.py
> +from selenium.webdriver.support.ui import WebDriverWait
위 코드로 변경시 민수님쪽에서는 안돌아가나요?

2023-05-03 01:45 UTC, usiohc commented
> 고생 많으셨습니다!! 코드 돌리는데 문제는 없었습니다 !! : D
> 
> ## venv 환경에서 돌리지 않고 local 에서 돌렸더니 잘 돌아간거였습니다 다른분들 확인해보셔야해요!!!!
> venv 환경 시 `pip3 install lxml ` 필요
> 
> ## elenium.common.exceptions.SessionNotCreatedException 에러 발생 시 참고
> 코드 안돌아가시는 분들 중 에러 메세지가 `selenium.common.exceptions.SessionNotCreatedException: ...` 처럼 뜨시는 분들은 사용중인Chrome 과 chromedriver.exe 의 버전이 맞지 않아서 나타나는 현상입니다.
> 
> 해결방법
> 
> 1. 크롬실행 -> 우측상단 (  ⋮ ) 클릭 -> 설정  ->  Chrome 정보 ->  버전 확인 ( ex : 버전 112.0.5615.137(공식 빌드) (arm64) )
> 2. 다운로드 사이트 접속 ( [링크](https://chromedriver.chromium.org/downloads) ) -> 버전과 맞는 driver 설치 ( xxx.x.xx...) 총 5~6자리만 맞으면 실행됩니다!
> 
> 3-1. windws 기존 branch에 존재하던 chromedriver.exe 삭제 후 다운로드 받은 exe 붙여놓기
> 
> 3-2. mac `$ xattr -d com.apple.quarantine chromedriver` 를 통하여 신용할 수 있는 어플로 변경 기존 branch에 존재하던 chromedriver.exe 삭제 후 다운로드 받은 `chromedriver` 붙여놓기
> 
> 다 했는데도 실행이 안된다면 152번째 줄에� `driver = webdriver.Chrome('chromedriver', options=options)` -> ` driver = webdriver.Chrome('./chromedriver', options=options)` 로 변경하면 해결이 될 수도 있습니다

정현님이 잘 정리해주셨습니다!!
만약 chrome 관련 설정을 건드리기 귀찮으시면

(https://github.com/TonysHub/subway/blob/cb2499e519e0380d74f51705228f9109a45d30be/project/crawler.py#L14)

위치의 주석들 해제해서

https://github.com/TonysHub/subway/blob/cb2499e519e0380d74f51705228f9109a45d30be/project/crawler.py#L152

에서 수정하고 테스트 하셔도 됩니다!

2023-05-03 04:28 UTC, TonysHub approved these changes
LGTM 💯

2023-05-03 05:07 UTC, Jeon-peng approved these changes
LGTM 👍

2023-05-03 05:08 UTC, usiohc commented
1. @Jeon-peng  @TonysHub 님이 언급하신 부분들 수정 완료
2. data to csv 진행하는 code 변경 (stackoverflow 참고)

2023-05-03 05:11 UTC, merged