Lds feature datascraping
TonysHub/subway pull request #7
Opened 2023-05-01 13:46 UTC by TonysHub

2023-05-01 13:51 UTC, Jeon-peng approved these changes
👍

2023-05-01 14:03 UTC, Jeon-peng requested changes
.ipynb 파일은 읽기가 좀 어렵습니다! 

파이썬 파일 (.py)로 변경 해서 부탁드립니다!

2023-05-01 16:07 UTC, TonysHub commented
> 

변경 완료했습니다

2023-05-02 02:20 UTC, usiohc commented on project/lds_scraper.py
> +            if current_date.year*12+current_date.month-(date_of_data.year*12+date_of_data.month) > 3:
정확하게는 기억이 잘 나지 않는데 datetime - datetime 이 가능했던 걸로 기억합니다!
해당 기능을 사용해 while True 를 사용하지않고 if문 제거, while 조건문에 한번에 표현할 수 있을 것 같아요

2023-05-02 02:31 UTC, TonysHub commented on project/lds_scraper.py
> +            if current_date.year*12+current_date.month-(date_of_data.year*12+date_of_data.month) > 3:
저도 여기서 엄청 시간 소모했는데, pd.TimeStamp.now() dtype이 datetime이 아니라 TimeStamp여서 복잡하게 됐습니다 ㅠㅠ

지금 찾아보니까 [to_pydatetime](https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.Timestamp.to_pydatetime.html#pandas.Timestamp.to_pydatetime)으로 먼저 변환하고 밑에처럼 subtract하면 될 것 같네요! 감사합니다

`df_test['Difference'] = (df_test['First_Date'] - df_test['Second Date']).dt.days`

2023-05-02 02:39 UTC, swanim commented on project/lds_scraper.py
> +            if current_date.year*12+current_date.month-(date_of_data.year*12+date_of_data.month) > 3:
3개월 이상 차이 나면 break 수행하도록 작성해 불필요한 데이터는 수집하지 않은 점이 좋아 보이네요!

2023-05-02 07:19 UTC, closed without merging